<div class="col col-login mx-auto">
    <div class="text-center mb-6">
        <img src="<?php echo $this->baseUrl('/demo/brand/tabler.svg') ?>" class="h-6" alt="">
    </div>

    <div class="card-body p-6">
        <div class="card-title">Login to your account</div>
        <?php
        $this->loginForm->setAction($this->url());
        echo $this->loginForm;
        ?>
    </div>
    <div class="text-center text-muted">
        Don't have account yet? <a href="/users/register">Sign up</a>
    </div>
</div>