<div class="page-header">
    <h1 class="page-title">
        Dashboard
    </h1>
</div>
<div class="row row-cards row-deck">
    <div class="col-sm-6 col-lg-3">
        <div class="card p-3">
            <div class="d-flex align-items-center">
                    <span class="stamp stamp-md bg-blue mr-3">
                      <i class="fe fe-dollar-sign"></i>
                    </span>
                <div>
                    <h4 class="m-0"><a href="javascript:void(0)">132 <small>Sales</small></a></h4>
                    <small class="text-muted">12 waiting payments</small>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="card p-3">
            <div class="d-flex align-items-center">
                    <span class="stamp stamp-md bg-green mr-3">
                      <i class="fe fe-shopping-cart"></i>
                    </span>
                <div>
                    <h4 class="m-0"><a href="javascript:void(0)">78 <small>Orders</small></a></h4>
                    <small class="text-muted">32 shipped</small>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="card p-3">
            <div class="d-flex align-items-center">
                    <span class="stamp stamp-md bg-red mr-3">
                      <i class="fe fe-users"></i>
                    </span>
                <div>
                    <h4 class="m-0"><a href="javascript:void(0)">1,352 <small>Users</small></a></h4>
                    <small class="text-muted">163 registered today</small>
                </div>
            </div>
        </div>
    </div>
</div>