CREATE TABLE guestbook (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(32) NOT NULL DEFAULT 'noemail@test.com',
  comment TEXT NULL,
  created DATETIME NOT NULL
);


CREATE TABLE users (
      id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
      email VARCHAR(255) NOT NULL,
      password VARCHAR(255) NOT NULL,
      password_salt VARCHAR(255) NOT NULL
    );