<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg order-lg-first">
                <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
                    <li class="nav-item">
                        <a href="/" class="nav-link"><i class="fe fe-home"></i> Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="/users/index" class="nav-link"><i class="fe fe-check-square"></i> Users</a>
                    </li>
                    <li class="nav-item">
                        <a href="/order/index" class="nav-link"><i class="fe fe-image"></i> Order</a>
                    </li>
                    <li class="nav-item">
                        <a href="/purchase/index" class="nav-link"><i class="fe fe-file-text"></i> Purchase</a>
                    </li>
                    <li class="nav-item">
                        <a href="/guestbook/index" class="nav-link"><i class="fe fe-file-text"></i> Guestbook</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>