<?php
/**
 * Class Purchases_IndexController
 */
class Purchases_IndexController extends AdminController
{
    /**
     * set common members here
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->purchaseService = new Purchases_Service_Purchase();
    }
    /**
     * Purchase entries list action
     */
    public function indexAction()
    {
        $this->view->entries = $this->purchaseService->getEntries();
    }

    public function storeAction()
    {
        $this->view->cardTitle = "New Purchase";
        $request = $this->getRequest();
        $purchaseForm = new Purchases_Form_Purchase();
        $purchase = new Purchases_Model_Purchase($purchaseForm->getValues());
        $mapper = new Purchases_Model_PurchaseMapper();

        if ($purchase_id = $request->getParam('id')) {
            $this->view->cardTitle = "Edit Purchase";
            $mapper->find($purchase_id, $purchase);
            $purchaseForm->populate($purchase->toArray());
            $purchaseForm->getElement('submit')->setLabel('Update')->setAttrib('class', 'btn btn-primary');
        }

        if ($request->isPost() && $purchaseForm->isValid($request->getPost())) {
            $purchase->setOptions($purchaseForm->getValues());
            $mapper->save($purchase);
            $this->_helper->FlashMessenger->addMessage(array('success' => "Purchase has been successfully store."));
            return $this->redirect('/purchases/index');
        }

        $this->view->purchaseForm = $purchaseForm;
    }

    /**
     * Delete action
     */
    public function deleteAction()
    {
        $purchaseId = $this->getRequest()->getParam('id');

        if ($this->getRequest()->isPost() && $purchaseId) {

            if ($this->purchaseService->delete($purchaseId)) {
                $this->_helper->FlashMessenger->addMessage(array('success' => "Purchase has been successfully deleted."));
            } else {
                $this->_helper->FlashMessenger->addMessage(array('danger' => "Some error occurred while deleting Purchase, Please try after some time."));
            }

            $this->redirect('/purchases');
        }

        throw new Zend_Controller_Response_Exception('Wrong parameter', 404);
    }
}